# rules.py

# Define a comprehensive set of rules with 100 diseases and their associated symptoms
rules = {
    'flu': ['fever', 'cough', 'sore throat', 'muscle aches', 'fatigue'],
    'cold': ['runny nose', 'sneezing', 'cough', 'sore throat', 'mild fever'],
    'allergy': ['sneezing', 'itchy eyes', 'runny nose', 'congestion', 'itchy skin'],
    'sinusitis': ['facial pain/pressure', 'nasal congestion', 'thick nasal discharge', 'loss of smell', 'cough'],
    'pneumonia': ['fever', 'cough', 'shortness of breath', 'chest pain', 'fatigue'],
    'bronchitis': ['persistent cough', 'production of mucus', 'wheezing', 'shortness of breath', 'chest discomfort'],
    'gastritis': ['stomach pain', 'nausea', 'vomiting', 'loss of appetite', 'indigestion'],
    'peptic ulcer': ['abdominal pain', 'nausea', 'vomiting', 'loss of appetite', 'bloating'],
    'diabetes mellitus': ['frequent urination', 'excessive thirst', 'extreme hunger', 'fatigue', 'blurred vision'],
    'hypertension': ['headaches', 'dizziness', 'shortness of breath', 'nosebleeds', 'chest pain'],
    'migraine': ['severe headache', 'nausea', 'sensitivity to light', 'sensitivity to sound', 'visual disturbances'],
    'asthma': ['shortness of breath', 'wheezing', 'coughing', 'chest tightness', 'difficulty breathing'],
    'chickenpox': ['itchy rash', 'fever', 'tiredness', 'loss of appetite', 'headache'],
    'measles': ['high fever', 'rash', 'cough', 'runny nose', 'red eyes'],
    'tuberculosis': ['persistent cough', 'weight loss', 'night sweats', 'fever', 'blood in sputum'],
    'hiv/aids': ['rapid weight loss', 'recurring fever', 'persistent cough', 'night sweats', 'extreme tiredness'],
    'hepatitis': ['jaundice', 'abdominal pain', 'nausea', 'fatigue', 'dark urine'],
    'rheumatoid arthritis': ['joint pain', 'swelling', 'stiffness', 'fatigue', 'fever'],
    'osteoarthritis': ['joint pain', 'stiffness', 'swelling', 'reduced range of motion', 'tenderness'],
    'parkinson\'s disease': ['tremors', 'muscle rigidity', 'bradykinesia', 'postural instability', 'changes in handwriting'],
    'epilepsy': ['seizures', 'loss of consciousness', 'muscle spasms', 'confusion', 'staring'],
    'bipolar disorder': ['mood swings', 'depression', 'mania', 'irritability', 'changes in sleep patterns'],
    'schizophrenia': ['hallucinations', 'delusions', 'disorganized thinking', 'flat affect', 'social withdrawal'],
    'depression': ['persistent sadness', 'loss of interest', 'fatigue', 'changes in appetite', 'sleep disturbances'],
    'anxiety disorder': ['excessive worry', 'restlessness', 'muscle tension', 'fatigue', 'difficulty concentrating'],
    'post-traumatic stress disorder': ['flashbacks', 'nightmares', 'severe anxiety', 'avoidance of reminders', 'hypervigilance'],
    'obsessive-compulsive disorder': ['obsessions', 'compulsions', 'recurrent thoughts', 'ritualistic behavior', 'distress'],
    'panic disorder': ['sudden panic attacks', 'palpitations', 'sweating', 'shortness of breath', 'dizziness'],
    'anorexia nervosa': ['severe weight loss', 'fear of gaining weight', 'distorted body image', 'restricted eating', 'excessive exercise'],
    'bulimia nervosa': ['binge eating', 'purging', 'guilt about eating', 'fluctuating weight', 'preoccupation with food'],
    'bacterial meningitis': ['severe headache', 'stiff neck', 'fever', 'nausea', 'sensitivity to light'],
    'viral meningitis': ['headache', 'fever', 'stiff neck', 'nausea', 'vomiting'],
    'multiple sclerosis': ['muscle weakness', 'difficulty with coordination', 'numbness', 'vision problems', 'fatigue'],
    'amyotrophic lateral sclerosis': ['muscle weakness', 'difficulty speaking', 'difficulty swallowing', 'muscle cramps', 'twitching'],
    'lupus': ['fatigue', 'joint pain', 'skin rash', 'fever', 'sensitivity to sunlight'],
    'scleroderma': ['skin thickening', 'Raynaud\'s phenomenon', 'joint pain', 'digestive issues', 'swelling'],
    'psoriasis': ['red patches of skin', 'itchy skin', 'scales', 'dry skin', 'nail changes'],
    'eczema': ['itchy skin', 'red patches', 'dry skin', 'blisters', 'inflammation'],
    'contact dermatitis': ['itchy rash', 'redness', 'swelling', 'blisters', 'dry patches'],
    'ringworm': ['ring-shaped rash', 'itchiness', 'scaling', 'redness', 'hair loss'],
    'athlete\'s foot': ['itchy feet', 'redness', 'peeling skin', 'burning sensation', 'blisters'],
    'jock itch': ['itchy groin', 'red rash', 'scaling', 'burning sensation', 'sores'],
    'tinea versicolor': ['discolored patches', 'scaling', 'itchiness', 'dry skin', 'uneven skin tone'],
    'shingles': ['painful rash', 'blisters', 'itchiness', 'fever', 'sensitivity'],
    'herpes simplex': ['painful sores', 'blisters', 'itching', 'burning sensation', 'fever'],
    'human papillomavirus': ['warts', 'genital warts', 'throat warts', 'itching', 'discomfort'],
    'chlamydia': ['discharge', 'painful urination', 'abdominal pain', 'vaginal bleeding', 'pain during intercourse'],
    'gonorrhea': ['discharge', 'painful urination', 'swollen testicles', 'vaginal discharge', 'pelvic pain'],
    'syphilis': ['sores', 'rash', 'fever', 'swollen lymph nodes', 'sore throat'],
    'trichomoniasis': ['vaginal discharge', 'itching', 'painful urination', 'abdominal pain', 'unusual smell'],
    'helicobacter pylori infection': ['abdominal pain', 'nausea', 'vomiting', 'bloating', 'loss of appetite'],
    'celiac disease': ['diarrhea', 'abdominal pain', 'bloating', 'weight loss', 'fatigue'],
    'irritable bowel syndrome': ['abdominal pain', 'bloating', 'gas', 'diarrhea', 'constipation'],
    'crohn\'s disease': ['abdominal pain', 'diarrhea', 'weight loss', 'fatigue', 'cramping'],
    'ulcerative colitis': ['abdominal pain', 'bloody diarrhea', 'weight loss', 'fever', 'fatigue'],
    'diverticulitis': ['abdominal pain', 'fever', 'nausea', 'vomiting', 'changes in bowel habits'],
    'appendicitis': ['abdominal pain', 'nausea', 'vomiting', 'fever', 'loss of appetite'],
    'gallstones': ['abdominal pain', 'nausea', 'vomiting', 'fever', 'jaundice'],
    'pancreatitis': ['abdominal pain', 'nausea', 'vomiting', 'fever', 'rapid pulse'],
    'kidney stones': ['severe pain', 'blood in urine', 'nausea', 'vomiting', 'frequent urination'],
    'chronic kidney disease': ['fatigue', 'swelling', 'shortness of breath', 'nausea', 'loss of appetite'],
    'bladder infection': ['painful urination', 'frequent urination', 'blood in urine', 'cloudy urine', 'pelvic pain'],
    'prostate infection': ['painful urination', 'frequent urination', 'pain in lower abdomen', 'fever', 'difficulty urinating'],
    'endometriosis': ['pelvic pain', 'heavy periods', 'pain during intercourse', 'nausea', 'fatigue'],
    'polycystic ovary syndrome': ['irregular periods', 'acne', 'weight gain', 'excessive hair growth', 'infertility'],
    'pregnancy': ['missed period', 'nausea', 'breast tenderness', 'fatigue', 'frequent urination'],
    'miscarriage': ['vaginal bleeding', 'abdominal cramping', 'passage of tissue', 'lower back pain', 'loss of pregnancy symptoms'],
    'ectopic pregnancy': ['abdominal pain', 'vaginal bleeding', 'shoulder pain', 'dizziness', 'fainting'],
    'menopause': ['hot flashes', 'irregular periods', 'vaginal dryness', 'mood swings', 'sleep disturbances'],
    'osteoporosis': ['bone pain', 'fractures', 'loss of height', 'stooped posture', 'back pain'],
    'rickets': ['bone pain', 'deformities', 'delayed growth', 'muscle weakness', 'skeletal deformities'],
    'scoliosis': ['uneven shoulders', 'uneven hips', 'back pain', 'visible curve in spine', 'postural changes'],
    'gout': ['sudden joint pain', 'swelling', 'redness', 'warmth', 'limited range of motion'],
    'liver cirrhosis': ['jaundice', 'abdominal swelling', 'fatigue', 'easy bruising', 'itchiness'],
    'autoimmune hepatitis': ['fatigue', 'abdominal pain', 'jaundice', 'dark urine', 'joint pain'],
    'hemophilia': ['easy bruising', 'prolonged bleeding', 'joint pain', 'nosebleeds', 'unexplained bleeding'],
    'leukemia': ['fatigue', 'frequent infections', 'easy bleeding', 'swollen lymph nodes', 'weight loss'],
    'lymphoma': ['swollen lymph nodes', 'fever', 'weight loss', 'night sweats', 'itching'],
    'myeloma': ['bone pain', 'fatigue', 'weakness', 'frequent infections', 'kidney problems'],
    'anemia': ['fatigue', 'paleness', 'shortness of breath', 'dizziness', 'cold hands and feet'],
    'iron deficiency anemia': ['fatigue', 'paleness', 'shortness of breath', 'brittle nails', 'cold extremities'],
    'vitamin B12 deficiency': ['fatigue', 'weakness', 'numbness', 'tingling', 'difficulty walking'],
    'folic acid deficiency': ['fatigue', 'weakness', 'irritability', 'shortness of breath', 'pale skin'],
    'chronic fatigue syndrome': ['persistent fatigue', 'muscle pain', 'joint pain', 'sore throat', 'unrefreshing sleep'],
    'systemic lupus erythematosus': ['fatigue', 'joint pain', 'skin rash', 'fever', 'kidney problems'],
    'vasculitis': ['fever', 'fatigue', 'weight loss', 'painful joints', 'skin rash'],
    'polyarteritis nodosa': ['fever', 'muscle pain', 'abdominal pain', 'skin rash', 'weight loss'],
    'giant cell arteritis': ['headache', 'vision problems', 'jaw pain', 'fever', 'scalp tenderness'],
    'temporal arteritis': ['headache', 'scalp tenderness', 'vision loss', 'jaw pain', 'fever'],
    'hypothyroidism': ['fatigue', 'weight gain', 'cold intolerance', 'constipation', 'dry skin'],
    'hyperthyroidism': ['weight loss', 'heat intolerance', 'tremors', 'palpitations', 'nervousness'],
    'thyroiditis': ['neck pain', 'fever', 'swelling in neck', 'fatigue', 'difficulty swallowing'],
    'goiter': ['swelling in neck', 'difficulty swallowing', 'coughing', 'tightness in throat', 'hoarseness'],
    'Addison\'s disease': ['fatigue', 'weight loss', 'darkening of skin', 'low blood pressure', 'dizziness'],
    'Cushing\'s syndrome': ['weight gain', 'round face', 'purple stretch marks', 'fatigue', 'high blood pressure'],
    'hyperparathyroidism': ['bone pain', 'kidney stones', 'abdominal pain', 'excessive thirst', 'fatigue'],
    'hypoparathyroidism': ['muscle cramps', 'tingling', 'seizures', 'fatigue', 'dry skin'],
    'primary biliary cholangitis': ['fatigue', 'itchy skin', 'jaundice', 'dry eyes', 'dark urine'],
    'primary sclerosing cholangitis': ['jaundice', 'abdominal pain', 'itchy skin', 'weight loss', 'fever'],
    'hemochromatosis': ['joint pain', 'fatigue', 'diabetes', 'heart problems', 'skin changes'],
    'Wilson\'s disease': ['tremors', 'difficulty speaking', 'personality changes', 'jaundice', 'abdominal pain'],
    'phenylketonuria': ['intellectual disability', 'seizures', 'delayed development', 'behavioral problems', 'musty odor'],
    'Maple syrup urine disease': ['poor feeding', 'vomiting', 'lethargy', 'developmental delay', 'sweet-smelling urine'],
    'Tay-Sachs disease': ['muscle weakness', 'loss of motor skills', 'deafness', 'blindness', 'cherry-red spot in the eye'],
    'Duchenne muscular dystrophy': ['muscle weakness', 'difficulty walking', 'enlarged calf muscles', 'frequent falls', 'scoliosis'],
    'Becker muscular dystrophy': ['muscle weakness', 'difficulty walking', 'enlarged calf muscles', 'muscle cramps', 'heart problems'],
}
